version = 1

[[annotations]]
path = [
  "README.md",
  "Cargo.lock",
  "go.sum",
  "PROJECT",
  "operator/src/kbs-config.toml",
  "operator/src/resource.rego",
  "operator/src/tpm.rego",
  "docs/pics/*",
  "docs/design/*",
  "docs/dev/*",
  "docs/usage/*",
  "lib/src/vendor_kopium/*",
  "must-gather/README.md",
  "tests/README.md",
  "examples/vm-coreos-ign.yaml",
  "scripts/install-kubevirt.sh"
]
SPDX-FileCopyrightText = [
    "Alice Frosi <afrosi@redhat.com>",
    "Jakob Naucke <jnaucke@redhat.com>"
]
SPDX-License-Identifier = "CC0-1.0"
